"""Domain models and enums."""

from enum import Enum


class ErrorCode(str, Enum):
    """Standardized error codes for API responses."""

    POLICY_NOT_FOUND = "POLICY_NOT_FOUND"
    INVALID_POLICY = "INVALID_POLICY"
    INVALID_CONSENSUS_DATA = "INVALID_CONSENSUS_DATA"
    INVALID_PRICE_TREND_RANGE = "INVALID_PRICE_TREND_RANGE"
    METRIC_NOT_FOUND = "METRIC_NOT_FOUND"
    EVENT_ROW_NOT_FOUND = "EVENT_ROW_NOT_FOUND"
    AMBIGUOUS_EVENT_DATE = "AMBIGUOUS_EVENT_DATE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
